# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Publish to Bintray (for Spigot 1.8-1.12)

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: bintray-roinujnosde-bukkit-plugins # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Bintray
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.BINTRAY_TOKEN }}
