name: Publish to Modrinth
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: 16
        cache: 'maven'
        distribution: 'temurin'
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
    - name: Upload artifact
      uses: RubixDev/modrinth-upload@v1.0.0
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        project_id: quLDfyDl
        file_path: target/SimpleClans.jar
        changelog: ${{ github.event.release.body }}
        name: ${{ github.event.release.tag_name }}
        version: ${{ github.event.release.tag_name }}
        game_versions: 1.21,1.20,1.19,1.18,1.17,1.16,1.15,1.14,1.13,1.12,1.11,1.10,1.9,1.8
        release_type: release
        loaders: spigot
        featured: true
